package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.model.DocumentVector;
import com.yizhaoqi.smartpai.repository.DocumentVectorRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    // 响应流安全网：仅当流超过此时长（毫秒）仍未结束时才强制结束，避免会话挂起。
    // 正常结束由 DeepSeekClient.streamResponse 的 onComplete 回调处理，不会提前截断答案/聊天记录。
    private static final long RESPONSE_MAX_WAIT_MS = 120000;
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final DocumentVectorRepository documentVectorRepository;
    private final ConversationSummaryService conversationSummaryService;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> fileMd5}
    private final Map<String, Map<Integer, String>> sessionReferenceMappings = new ConcurrentHashMap<>();
    // 用于存储每个会话的用户ID：sessionId -> userId
    private final Map<String, String> sessionUserMapping = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      DocumentVectorRepository documentVectorRepository,
                      ConversationSummaryService conversationSummaryService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.documentVectorRepository = documentVectorRepository;
        this.conversationSummaryService = conversationSummaryService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            // 0. 保存会话与用户的映射关系
            sessionUserMapping.put(session.getId(), userId);
            
            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取对话历史
            List<Map<String, String>> fullHistory = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", fullHistory.size());

            // 3. 对话摘要：将完整历史压缩为摘要+近期消息，减少 token 消耗
            List<Map<String, String>> history = conversationSummaryService
                    .getContextWithSummary(conversationId, fullHistory);

            // 4. 执行 RAG 检索流程
            // 4.1 执行带权限过滤的混合搜索
            List<SearchResult> searchResults = searchService.searchWithPermission(userMessage, userId, 5);
            logger.debug("搜索结果数量: {}", searchResults.size());

            // 4.2 构建上下文（RAG 检索结果）
            String context = buildContext(searchResults, session.getId());
            
            // 8. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history,
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                },
                () -> {
                    // 流式响应正常结束：保存完整对话，不再依赖脆弱的“2秒无新增就结束”判断
                    StringBuilder rb = responseBuilders.get(session.getId());
                    if (rb != null) {
                        completeResponse(rb, responseFuture, session, conversationId, userId, userMessage);
                    }
                });
            
            // 7. 安全网：仅在响应流长时间未结束时强制结束，避免会话挂起。
            // 正常结束由 streamResponse 的 onComplete 回调处理，此处不会提前截断答案/聊天记录。
            new Thread(() -> {
                try {
                    long deadline = System.currentTimeMillis() + RESPONSE_MAX_WAIT_MS;
                    while (!responseFuture.isDone() && System.currentTimeMillis() < deadline) {
                        Thread.sleep(5000);
                    }
                    if (!responseFuture.isDone()) {
                        StringBuilder rb = responseBuilders.get(session.getId());
                        if (rb != null) {
                            logger.warn("响应流超过 {}ms 未结束，强制完成对话", RESPONSE_MAX_WAIT_MS);
                            completeResponse(rb, responseFuture, session, conversationId, userId, userMessage);
                        } else {
                            logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", session.getId());
                            RuntimeException exception = new RuntimeException("响应构建器为空");
                            responseFuture.completeExceptionally(exception);
                            handleError(session, exception);
                        }
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                }
            }).start();
            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理会话响应构建器
            responseBuilders.remove(session.getId());
            // 清理响应future
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 添加助手回复（带时间戳）
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的30条消息（摘要服务会进一步压缩）
        if (history.size() > 30) {
            history = history.subList(history.size() - 30, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    /**
     * 构建 AI 对话上下文
     * 实现 Parent Chunk 上下文扩展：检索时用子切片精准匹配，返回时回溯父块获取更大上下文
     *
     * @param searchResults RAG 检索结果列表
     * @param sessionId 会话ID
     * @return 构建的上下文文本
     */
    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        StringBuilder context = new StringBuilder();

        // 添加 RAG 检索结果
        if (searchResults != null && !searchResults.isEmpty()) {
            // 创建当前会话的引用映射
            Map<Integer, String> referenceMapping = new HashMap<>();

            final int MAX_PARENT_CHUNK_LEN = 1500; // 父块最长字符数，超出截断
            for (int i = 0; i < searchResults.size(); i++) {
                SearchResult result = searchResults.get(i);
                String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
                String fileMd5 = result.getFileMd5();
                Integer chunkId = result.getChunkId();

                // 尝试获取父块内容（Parent Chunk 扩展）
                String snippet = getParentChunkContent(fileMd5, chunkId, MAX_PARENT_CHUNK_LEN);

                // 如果父块扩展失败或返回内容为空，使用 ES 检索结果中的原始文本作为降级方案
                if (snippet == null || snippet.trim().isEmpty()) {
                    snippet = truncateText(result.getTextContent(), MAX_PARENT_CHUNK_LEN);
                    logger.info("父块扩展为空，降级使用ES检索原始内容: fileMd5={}, 内容长度={}",
                            fileMd5, snippet.length());
                }

                // 格式：[1] (test1.txt | MD5:abc123def456) 文件内容...
                context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));

                // 保存引用编号到MD5的映射
                if (fileMd5 != null) {
                    referenceMapping.put(i + 1, fileMd5);
                    logger.info("引用映射: sessionId={}, 引用编号#{}={}, 文件名={}, MD5={}",
                        sessionId, i + 1, fileLabel, fileMd5);
                }
            }

            // 保存当前会话的引用映射
            sessionReferenceMappings.put(sessionId, referenceMapping);
            logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);
        }

        return context.toString();
    }

    /**
     * 获取父块内容（Parent Chunk 上下文扩展）
     * 根据 fileMd5 和 chunkId 查询该 chunk 所属的父块，合并同一父块的所有子切片
     *
     * @param fileMd5 文件 MD5
     * @param chunkId 子切片 ID
     * @param maxLen 最大长度限制
     * @return 父块内容文本
     */
    private String getParentChunkContent(String fileMd5, Integer chunkId, int maxLen) {
        if (fileMd5 == null || chunkId == null) {
            return "";
        }

        try {
            // 查询该 chunk 的 parentChunkId
            DocumentVector chunk = documentVectorRepository.findByFileMd5AndChunkId(fileMd5, chunkId);
            if (chunk == null || chunk.getParentChunkId() == null) {
                // 没有父块信息，返回原始内容
                return chunk != null ? truncateText(chunk.getTextContent(), maxLen) : "";
            }

            Integer parentChunkId = chunk.getParentChunkId();

            // 查询同一父块的所有子切片
            List<DocumentVector> siblingChunks = documentVectorRepository
                    .findByFileMd5AndParentChunkId(fileMd5, parentChunkId);

            if (siblingChunks.isEmpty()) {
                return truncateText(chunk.getTextContent(), maxLen);
            }

            // 按 chunkId 排序并合并文本
            siblingChunks.sort((a, b) -> Integer.compare(a.getChunkId(), b.getChunkId()));
            StringBuilder parentContent = new StringBuilder();
            for (DocumentVector sibling : siblingChunks) {
                if (sibling.getTextContent() != null) {
                    if (parentContent.length() > 0) {
                        parentContent.append("\n\n");
                    }
                    parentContent.append(sibling.getTextContent());
                }
            }

            String result = truncateText(parentContent.toString(), maxLen);
            logger.debug("Parent Chunk 扩展: fileMd5={}, chunkId={}, parentChunkId={}, 子切片数={}, 合并后长度={}",
                    fileMd5, chunkId, parentChunkId, siblingChunks.size(), result.length());
            return result;

        } catch (Exception e) {
            logger.warn("获取父块内容失败，降级使用原始内容: fileMd5={}, chunkId={}", fileMd5, chunkId, e);
            // 降级：查询原始 chunk 内容
            try {
                DocumentVector chunk = documentVectorRepository.findByFileMd5AndChunkId(fileMd5, chunkId);
                return chunk != null ? truncateText(chunk.getTextContent(), maxLen) : "";
            } catch (Exception ex) {
                return "";
            }
        }
    }

    /**
     * 截断文本到指定长度
     *
     * @param text 原始文本
     * @param maxLen 最大长度
     * @return 截断后的文本
     */
    private String truncateText(String text, int maxLen) {
        if (text == null) {
            return "";
        }
        if (text.length() <= maxLen) {
            return text;
        }
        return text.substring(0, maxLen) + "…";
    }

    /**
     * 完成响应处理的辅助方法
     * 统一处理响应完成后的操作，包括更新对话历史
     *
     * @param responseBuilder 响应构建器
     * @param responseFuture 响应未来对象
     * @param session WebSocket 会话
     * @param conversationId 会话ID
     * @param userId 用户ID
     * @param userMessage 用户消息
     */
    private void completeResponse(StringBuilder responseBuilder,
                                   CompletableFuture<String> responseFuture,
                                   WebSocketSession session,
                                   String conversationId,
                                   String userId,
                                   String userMessage) {
        // 防止 watcher 线程与流式完成回调重复触发，导致历史被存两次
        if (responseFuture.isDone()) {
            return;
        }
        String completeResponse = responseBuilder.toString();
        responseFuture.complete(completeResponse);
        logger.info("DeepSeek响应已完成，长度: {}", completeResponse.length());

        // 发送响应完成通知
        sendCompletionNotification(session);

        // 更新对话历史
        onConversationComplete(conversationId, userId, userMessage, completeResponse, session.getId());

        // 清理会话响应构建器
        responseBuilders.remove(session.getId());
        responseFutures.remove(session.getId());
        logger.info("消息处理完成，用户ID: {}", userId);
    }

    /**
     * 对话完成后的回调方法
     * 负责更新对话历史
     *
     * @param conversationId 会话ID
     * @param userId 用户ID
     * @param userMessage 用户消息
     * @param aiResponse AI 回复
     * @param sessionId WebSocket 会话ID
     */
    private void onConversationComplete(String conversationId, String userId,
                                         String userMessage, String aiResponse,
                                         String sessionId) {
        // 1. 更新 Redis 中的对话历史
        updateConversationHistory(conversationId, userMessage, aiResponse);

        // 2. 清理会话用户映射
        sessionUserMapping.remove(sessionId);

        // 输出对话存储信息以便调试
        String redisKey = "user:" + userId + ":current_conversation";
        logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        // 设置停止标志
        stopFlags.put(sessionId, true);

        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop",
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }

        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    /**
     * 根据会话ID和引用编号获取文件MD5
     *
     * @param sessionId WebSocket会话ID
     * @param referenceNumber 引用编号
     * @return 文件MD5，如果找不到则返回null
     */
    public String getReferenceMd5(String sessionId, int referenceNumber) {
        logger.info("查询引用MD5: sessionId={}, referenceNumber=#{}", sessionId, referenceNumber);

        Map<Integer, String> referenceMapping = sessionReferenceMappings.get(sessionId);
        if (referenceMapping == null) {
            logger.error("未找到会话 {} 的引用映射，当前所有会话: {}", sessionId, sessionReferenceMappings.keySet());
            return null;
        }

        logger.info("会话 {} 的引用映射内容: {}", sessionId, referenceMapping);

        String fileMd5 = referenceMapping.get(referenceNumber);
        if (fileMd5 == null) {
            logger.error("会话 {} 中未找到引用编号 #{}, 可用的引用编号: {}", sessionId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("成功找到引用映射: sessionId={}, referenceNumber=#{}, fileMd5={}", sessionId, referenceNumber, fileMd5);
        return fileMd5;
    }

    /**
     * 清理会话的引用映射
     *
     * @param sessionId WebSocket会话ID
     */
    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, String> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("清理会话 {} 的引用映射，共 {} 条", sessionId, removed.size());
        }
    }
}
