package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.config.SensitiveWordConfig;
import com.yizhaoqi.smartpai.config.SensitiveWordFilter;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.model.DocumentChunk;
import com.yizhaoqi.smartpai.repository.DocumentChunkRepository;
import com.yizhaoqi.smartpai.service.ConversationService;
import com.yizhaoqi.smartpai.utils.LogUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Service;
import reactor.core.Disposable;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理 SSE 聊天消息和管理对话历史。
 * 传输通道通过 {@link ChatOutput} 抽象，与具体协议（原 WebSocket / 现 SSE）解耦。
 *
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {

    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    // 响应流安全网：仅当流超过此时长（毫秒）仍未结束时才强制结束，避免会话挂起。
    private static final long RESPONSE_MAX_WAIT_MS = 120000;
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final DocumentChunkRepository documentChunkRepository;
    private final ConversationSummaryService conversationSummaryService;
    private final ConversationService conversationService;
    private final SensitiveWordConfig sensitiveWordConfig;
    private final SensitiveWordFilter sensitiveWordFilter;
    private final ObjectMapper objectMapper;
    private final ThreadPoolTaskExecutor taskExecutor;

    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 输出侧敏感词拦截标志：命中后本会话的回复将被拦截、不落库
    private final Map<String, Boolean> blockedFlags = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> fileMd5}
    private final Map<String, Map<Integer, String>> sessionReferenceMappings = new ConcurrentHashMap<>();
    // 用于存储每个会话的用户ID：sessionId -> userId
    private final Map<String, String> sessionUserMapping = new ConcurrentHashMap<>();
    // 活跃 LLM 订阅句柄：sessionId -> Disposable，用于停止时真正中断流
    private final Map<String, Disposable> activeDisposables = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                       HybridSearchService searchService,
                       DeepSeekClient deepSeekClient,
                       DocumentChunkRepository documentChunkRepository,
                       ConversationSummaryService conversationSummaryService,
                       ConversationService conversationService,
                       SensitiveWordConfig sensitiveWordConfig,
                       SensitiveWordFilter sensitiveWordFilter) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.documentChunkRepository = documentChunkRepository;
        this.conversationSummaryService = conversationSummaryService;
        this.conversationService = conversationService;
        this.sensitiveWordConfig = sensitiveWordConfig;
        this.sensitiveWordFilter = sensitiveWordFilter;
        this.objectMapper = new ObjectMapper();

        // SSE 场景：流式生成在独立线程执行，避免阻塞 HTTP 请求线程
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(8);
        executor.setMaxPoolSize(32);
        executor.setQueueCapacity(256);
        executor.setThreadNamePrefix("chat-sse-");
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.initialize();
        this.taskExecutor = executor;
    }

    public void processMessage(String userId, String userMessage, ChatOutput output) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, output.getId());
        // 在独立线程执行，避免阻塞 SSE HTTP 请求线程
        taskExecutor.submit(() -> runProcessMessage(userId, userMessage, output));
    }

    private void runProcessMessage(String userId, String userMessage, ChatOutput output) {
        final String sessionId = output.getId();
        try {
            // 0. 保存会话与用户的映射关系
            sessionUserMapping.put(sessionId, userId);

            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);

            // 将当前会话ID回传给前端，确保前后端会话状态同步（修复历史会话切换/高亮不一致问题）
            sendConversationId(output, conversationId);

            // 为当前会话创建响应构建器
            responseBuilders.put(sessionId, new StringBuilder());
            // 重置输出侧敏感词拦截标志
            blockedFlags.remove(sessionId);
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(sessionId, responseFuture);

            // 2. 获取对话历史
            List<Map<String, String>> fullHistory = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", fullHistory.size());

            // 3. 对话摘要：将完整历史压缩为摘要+近期消息，减少 token 消耗
            List<Map<String, String>> history = conversationSummaryService
                    .getContextWithSummary(conversationId, fullHistory);

            // 4. 执行 RAG 检索流程
            // 4.1 执行带权限过滤的混合搜索
            List<SearchResult> searchResults = searchService.searchWithPermission(userMessage, userId, 5);
            logger.debug("搜索结果数量: {}", searchResults.size());

            // 4.2 构建上下文（RAG 检索结果）
            String context = buildContext(searchResults, sessionId);

            // 8. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            Disposable disposable = deepSeekClient.streamResponse(userMessage, context, history,
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(sessionId);
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    // 输出侧敏感词拦截：一旦累积内容命中敏感词，立即标记并停止推送
                    if (Boolean.FALSE.equals(blockedFlags.get(sessionId))) {
                        // 已经判定拦截，直接丢弃后续 chunk
                        return;
                    }
                    if (sensitiveWordFilter != null && sensitiveWordFilter.contains(responseBuilder == null ? "" : responseBuilder.toString())) {
                        blockedFlags.put(sessionId, true);
                        logger.warn("AI 输出命中敏感词，会话 {} 将被拦截，不向前端推送完整内容", sessionId);
                        return;
                    }
                    sendResponseChunk(output, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(output, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(output);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(sessionId);
                    responseFutures.remove(sessionId);
                    activeDisposables.remove(sessionId);
                },
                () -> {
                    // 流式响应正常结束：保存完整对话，不再依赖脆弱的“2秒无新增就结束”判断
                    StringBuilder rb = responseBuilders.get(sessionId);
                    if (rb != null) {
                        completeResponse(rb, responseFuture, output, conversationId, userId, userMessage);
                    }
                    activeDisposables.remove(sessionId);
                });
            activeDisposables.put(sessionId, disposable);

            // 7. 安全网：仅在响应流长时间未结束时强制结束，避免会话挂起。
            new Thread(() -> {
                try {
                    long deadline = System.currentTimeMillis() + RESPONSE_MAX_WAIT_MS;
                    while (!responseFuture.isDone() && System.currentTimeMillis() < deadline) {
                        Thread.sleep(5000);
                    }
                    if (!responseFuture.isDone()) {
                        StringBuilder rb = responseBuilders.get(sessionId);
                        if (rb != null) {
                            logger.warn("响应流超过 {}ms 未结束，强制完成对话", RESPONSE_MAX_WAIT_MS);
                            completeResponse(rb, responseFuture, output, conversationId, userId, userMessage);
                        } else {
                            logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", sessionId);
                            RuntimeException exception = new RuntimeException("响应构建器为空");
                            responseFuture.completeExceptionally(exception);
                            handleError(output, exception);
                        }
                    }
                    activeDisposables.remove(sessionId);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    responseBuilders.remove(sessionId);
                    responseFutures.remove(sessionId);
                    activeDisposables.remove(sessionId);
                }
            }).start();

        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(output, e);
            // 清理会话响应构建器
            responseBuilders.remove(sessionId);
            // 清理响应future
            CompletableFuture<String> future = responseFutures.remove(sessionId);
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
            activeDisposables.remove(sessionId);
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);

        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }

        return conversationId;
    }

    /**
     * 新建会话 - 清除当前会话，创建全新的会话ID
     * 用于减少 token 消耗，避免历史对话过长
     */
    public String createNewConversation(String userId) {
        String oldKey = "user:" + userId + ":current_conversation";
        String oldConversationId = redisTemplate.opsForValue().get(oldKey);

        if (oldConversationId != null) {
            String historyKey = "conversation:" + oldConversationId;
            String historyJson = redisTemplate.opsForValue().get(historyKey);
            if (historyJson != null && !historyJson.isEmpty()) {
                saveConversationToHistory(userId, oldConversationId);
            }
            redisTemplate.delete(oldKey);
        }

        String newConversationId = UUID.randomUUID().toString();
        redisTemplate.opsForValue().set(oldKey, newConversationId, Duration.ofDays(7));
        initConversationMetadata(userId, newConversationId);

        logger.info("为用户 {} 创建全新会话ID: {} (旧会话: {})", userId, newConversationId, oldConversationId);
        return newConversationId;
    }

    /**
     * 获取用户的历史会话列表
     */
    public List<Map<String, Object>> getConversationHistoryList(String userId) {
        String listKey = "user:" + userId + ":conversation_list";

        try {
            redisTemplate.opsForZSet().zCard(listKey);
        } catch (Exception e) {
            logger.warn("会话列表键类型异常，重建为 ZSet: {}", listKey);
            redisTemplate.delete(listKey);
        }

        Set<String> conversationIds = redisTemplate.opsForZSet().reverseRange(listKey, 0, 19);

        List<Map<String, Object>> result = new ArrayList<>();
        if (conversationIds == null || conversationIds.isEmpty()) {
            return result;
        }

        for (String conversationId : conversationIds) {
            String metaKey = "conversation_meta:" + conversationId;
            String metaJson = redisTemplate.opsForValue().get(metaKey);
            String historyKey = "conversation:" + conversationId;
            String historyJson = redisTemplate.opsForValue().get(historyKey);

            if (historyJson == null || historyJson.isEmpty()) {
                List<Map<String, String>> mysqlHistory = conversationService.getHistoryFromMysql(conversationId);
                if (mysqlHistory.isEmpty()) {
                    redisTemplate.opsForZSet().remove(listKey, conversationId);
                    redisTemplate.delete(metaKey);
                    logger.info("清理无历史记录的脏数据会话: {}", conversationId);
                    continue;
                }
                logger.info("会话 {} 的 Redis 历史已过期，从 MySQL 兜底还原", conversationId);
                ensureConversationMeta(userId, conversationId, mysqlHistory);
                historyJson = redisTemplate.opsForValue().get(historyKey);
                if (metaJson == null) {
                    metaJson = redisTemplate.opsForValue().get(metaKey);
                }
            }

            if (metaJson != null) {
                try {
                    Map<String, Object> meta = objectMapper.readValue(metaJson, new TypeReference<Map<String, Object>>() {});
                    List<Map<String, String>> history = objectMapper.readValue(historyJson, new TypeReference<List<Map<String, String>>>() {});
                    int messageCount = history.size();
                    meta.put("conversationId", conversationId);
                    meta.put("messageCount", messageCount);
                    result.add(meta);
                } catch (JsonProcessingException e) {
                    logger.error("解析会话元数据失败: {}", e.getMessage());
                }
            }
        }

        logger.info("获取用户 {} 的历史会话列表，共 {} 个", userId, result.size());
        return result;
    }

    /**
     * 切换到指定的历史会话
     */
    public List<Map<String, String>> switchToConversation(String userId, String conversationId) {
        if (conversationId == null || conversationId.isEmpty()) {
            throw new IllegalArgumentException("会话ID不能为空");
        }

        String listKey = "user:" + userId + ":conversation_list";
        Boolean isMember = redisTemplate.opsForZSet().score(listKey, conversationId) != null;
        String currentKey = "user:" + userId + ":current_conversation";
        String currentConversationId = redisTemplate.opsForValue().get(currentKey);

        if (!isMember && !conversationId.equals(currentConversationId)) {
            String historyKey = "conversation:" + conversationId;
            String historyJson = redisTemplate.opsForValue().get(historyKey);
            if (historyJson == null || historyJson.isEmpty()) {
                throw new RuntimeException("会话不存在或不属于当前用户");
            }
            saveConversationToHistory(userId, conversationId);
        }

        if (currentConversationId != null && !currentConversationId.equals(conversationId)) {
            String historyKey = "conversation:" + currentConversationId;
            String historyJson = redisTemplate.opsForValue().get(historyKey);
            if (historyJson != null && !historyJson.isEmpty()) {
                saveConversationToHistory(userId, currentConversationId);
            }
        }

        redisTemplate.opsForValue().set(currentKey, conversationId, Duration.ofDays(7));

        List<Map<String, String>> history = getConversationHistory(conversationId);
        if (history.isEmpty()) {
            history = conversationService.getHistoryFromMysql(conversationId);
            if (!history.isEmpty()) {
                try {
                    redisTemplate.opsForValue().set("conversation:" + conversationId,
                            objectMapper.writeValueAsString(history), Duration.ofDays(7));
                    logger.info("会话 {} 历史已从 MySQL 兜底还原并回写 Redis", conversationId);
                } catch (Exception e) {
                    logger.error("回写 Redis 失败（不影响返回）: {}", e.getMessage());
                }
                ensureConversationMeta(userId, conversationId, history);
            }
        }

        logger.info("用户 {} 切换到会话 {}，包含 {} 条消息", userId, conversationId, history.size());
        return history;
    }

    /**
     * 删除指定的历史会话
     */
    public void deleteConversation(String userId, String conversationId) {
        String listKey = "user:" + userId + ":conversation_list";
        redisTemplate.opsForZSet().remove(listKey, conversationId);
        String historyKey = "conversation:" + conversationId;
        redisTemplate.delete(historyKey);
        String metaKey = "conversation_meta:" + conversationId;
        redisTemplate.delete(metaKey);
        String currentKey = "user:" + userId + ":current_conversation";
        String currentConversationId = redisTemplate.opsForValue().get(currentKey);
        if (conversationId != null && conversationId.equals(currentConversationId)) {
            redisTemplate.delete(currentKey);
        }
        logger.info("用户 {} 删除会话 {}", userId, conversationId);
    }

    private void saveConversationToHistory(String userId, String conversationId) {
        String listKey = "user:" + userId + ":conversation_list";

        try {
            redisTemplate.opsForZSet().zCard(listKey);
        } catch (Exception e) {
            logger.warn("会话列表键类型异常，重建为 ZSet: {}", listKey);
            redisTemplate.delete(listKey);
        }

        double score = System.currentTimeMillis() / 1000.0;
        redisTemplate.opsForZSet().add(listKey, conversationId, score);
        redisTemplate.expire(listKey, Duration.ofDays(30));
        updateConversationMetadata(conversationId);
        logger.debug("保存会话 {} 到用户 {} 的历史列表", conversationId, userId);
    }

    private void initConversationMetadata(String userId, String conversationId) {
        String metaKey = "conversation_meta:" + conversationId;
        String now = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        Map<String, Object> meta = new HashMap<>();
        meta.put("title", "新会话");
        meta.put("createdAt", now);
        meta.put("updatedAt", now);
        try {
            String json = objectMapper.writeValueAsString(meta);
            redisTemplate.opsForValue().set(metaKey, json, Duration.ofDays(30));
        } catch (JsonProcessingException e) {
            logger.error("序列化会话元数据失败: {}", e.getMessage());
        }
    }

    private void updateConversationMetadata(String conversationId) {
        String metaKey = "conversation_meta:" + conversationId;
        String metaJson = redisTemplate.opsForValue().get(metaKey);
        if (metaJson == null) return;
        try {
            Map<String, Object> meta = objectMapper.readValue(metaJson, new TypeReference<Map<String, Object>>() {});
            String now = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
            meta.put("updatedAt", now);
            String json = objectMapper.writeValueAsString(meta);
            redisTemplate.opsForValue().set(metaKey, json, Duration.ofDays(30));
        } catch (JsonProcessingException e) {
            logger.error("更新会话元数据失败: {}", e.getMessage());
        }
    }

    public void updateConversationTitle(String conversationId, String firstMessage) {
        String metaKey = "conversation_meta:" + conversationId;
        String metaJson = redisTemplate.opsForValue().get(metaKey);
        if (metaJson == null) return;
        try {
            Map<String, Object> meta = objectMapper.readValue(metaJson, new TypeReference<Map<String, Object>>() {});
            if ("新会话".equals(meta.get("title"))) {
                String title = firstMessage.length() > 20 ? firstMessage.substring(0, 20) + "..." : firstMessage;
                meta.put("title", title);
                String json = objectMapper.writeValueAsString(meta);
                redisTemplate.opsForValue().set(metaKey, json, Duration.ofDays(30));
                logger.info("更新会话 {} 标题为: {}", conversationId, title);
            }
        } catch (JsonProcessingException e) {
            logger.error("更新会话标题失败: {}", e.getMessage());
        }
    }

    private void ensureConversationMeta(String userId, String conversationId, List<Map<String, String>> history) {
        String historyKey = "conversation:" + conversationId;
        if (redisTemplate.opsForValue().get(historyKey) == null) {
            try {
                redisTemplate.opsForValue().set(historyKey,
                        objectMapper.writeValueAsString(history), Duration.ofDays(7));
            } catch (Exception e) {
                logger.error("兜底回写会话历史失败: {}", e.getMessage());
            }
        }

        String metaKey = "conversation_meta:" + conversationId;
        String metaJson = redisTemplate.opsForValue().get(metaKey);
        if (metaJson == null) {
            String now = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
            String title = "历史会话";
            for (Map<String, String> msg : history) {
                if ("user".equals(msg.get("role"))) {
                    String content = msg.get("content");
                    if (content != null && !content.isEmpty()) {
                        title = content.length() > 20 ? content.substring(0, 20) + "..." : content;
                    }
                    break;
                }
            }
            Map<String, Object> meta = new HashMap<>();
            meta.put("title", title);
            meta.put("createdAt", now);
            meta.put("updatedAt", now);
            try {
                redisTemplate.opsForValue().set(metaKey, objectMapper.writeValueAsString(meta), Duration.ofDays(30));
            } catch (JsonProcessingException e) {
                logger.error("兜底还原会话元数据失败: {}", e.getMessage());
            }
        }
        saveConversationToHistory(userId, conversationId);
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));

        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);

        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);

        if (history.size() > 30) {
            history = history.subList(history.size() - 30, history.size());
        }

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
            if (history.size() == 2) {
                updateConversationTitle(conversationId, userMessage);
            }
            updateConversationMetadata(conversationId);
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        StringBuilder context = new StringBuilder();

        if (searchResults != null && !searchResults.isEmpty()) {
            Map<Integer, String> referenceMapping = new HashMap<>();
            final int MAX_PARENT_CHUNK_LEN = 1500;
            for (int i = 0; i < searchResults.size(); i++) {
                SearchResult result = searchResults.get(i);
                String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
                String fileMd5 = result.getFileMd5();
                Integer chunkId = result.getChunkId();

                String snippet = getParentChunkContent(fileMd5, chunkId, MAX_PARENT_CHUNK_LEN);
                if (snippet == null || snippet.trim().isEmpty()) {
                    snippet = truncateText(result.getTextContent(), MAX_PARENT_CHUNK_LEN);
                    logger.info("父块扩展为空，降级使用ES检索原始内容: fileMd5={}, 内容长度={}",
                            fileMd5, snippet.length());
                }

                context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));
                if (fileMd5 != null) {
                    referenceMapping.put(i + 1, fileMd5);
                    logger.info("引用映射: sessionId={}, 引用编号#{}={}, 文件名={}, MD5={}",
                        sessionId, i + 1, fileLabel, fileMd5);
                }
            }
            sessionReferenceMappings.put(sessionId, referenceMapping);
            logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);
        }

        return context.toString();
    }

    private String getParentChunkContent(String fileMd5, Integer chunkId, int maxLen) {
        if (fileMd5 == null || chunkId == null) {
            return "";
        }
        try {
            DocumentChunk chunk = documentChunkRepository.findByFileMd5AndChunkId(fileMd5, chunkId);
            if (chunk == null || chunk.getParentChunkId() == null) {
                return chunk != null ? truncateText(chunk.getTextContent(), maxLen) : "";
            }
            Integer parentChunkId = chunk.getParentChunkId();
            List<DocumentChunk> siblingChunks = documentChunkRepository
                    .findByFileMd5AndParentChunkId(fileMd5, parentChunkId);
            if (siblingChunks.isEmpty()) {
                return truncateText(chunk.getTextContent(), maxLen);
            }
            siblingChunks.sort((a, b) -> Integer.compare(a.getChunkId(), b.getChunkId()));
            StringBuilder parentContent = new StringBuilder();
            for (DocumentChunk sibling : siblingChunks) {
                if (sibling.getTextContent() != null) {
                    if (parentContent.length() > 0) {
                        parentContent.append("\n\n");
                    }
                    parentContent.append(sibling.getTextContent());
                }
            }
            String result = truncateText(parentContent.toString(), maxLen);
            logger.debug("Parent Chunk 扩展: fileMd5={}, chunkId={}, parentChunkId={}, 子切片数={}, 合并后长度={}",
                    fileMd5, chunkId, parentChunkId, siblingChunks.size(), result.length());
            return result;
        } catch (Exception e) {
            logger.warn("获取父块内容失败，降级使用原始内容: fileMd5={}, chunkId={}", fileMd5, chunkId, e);
            try {
                DocumentChunk chunk = documentChunkRepository.findByFileMd5AndChunkId(fileMd5, chunkId);
                return chunk != null ? truncateText(chunk.getTextContent(), maxLen) : "";
            } catch (Exception ex) {
                return "";
            }
        }
    }

    private String truncateText(String text, int maxLen) {
        if (text == null) {
            return "";
        }
        if (text.length() <= maxLen) {
            return text;
        }
        return text.substring(0, maxLen) + "…";
    }

    private void completeResponse(StringBuilder responseBuilder,
                                   CompletableFuture<String> responseFuture,
                                   ChatOutput output,
                                   String conversationId,
                                   String userId,
                                   String userMessage) {
        if (responseFuture.isDone()) {
            return;
        }
        String completeResponse = responseBuilder.toString();
        responseFuture.complete(completeResponse);
        logger.info("DeepSeek响应已完成，长度: {}", completeResponse.length());

        if (Boolean.TRUE.equals(blockedFlags.get(output.getId()))) {
            Set<String> hits = sensitiveWordFilter != null ? sensitiveWordFilter.findAll(completeResponse) : Set.of();
            String audit = String.format(
                    "AI输出敏感词拦截: 用户=%s 会话=%s 命中词=%s IP=%s 回复长度=%d（未落库）",
                    userId, output.getId(), hits, output.getClientIp(), completeResponse.length());
            if (sensitiveWordConfig.isAuditLog()) {
                LogUtils.logAudit("AI_OUTPUT_SENSITIVE_BLOCKED", audit);
            } else {
                logger.warn(audit);
            }
            try {
                sendRefuseMessage(output,
                        sensitiveWordConfig.getRejectMessage()
                                + "（AI 回复命中敏感词：" + String.join("、", hits) + "，已拦截未保存）");
            } catch (Exception e) {
                logger.error("发送 AI 输出拦截提示失败: {}", e.getMessage(), e);
            }
            try {
                sendCompletionNotification(output);
            } catch (Exception ignored) {
            }
            blockedFlags.remove(output.getId());
            responseBuilders.remove(output.getId());
            responseFutures.remove(output.getId());
            logger.info("AI 输出因敏感词被拦截，已终止，用户ID: {}", userId);
            return;
        }

        sendCompletionNotification(output);
        onConversationComplete(conversationId, userId, userMessage, completeResponse, output.getId());
        responseBuilders.remove(output.getId());
        responseFutures.remove(output.getId());
        logger.info("消息处理完成，用户ID: {}", userId);
    }

    private void onConversationComplete(String conversationId, String userId,
                                         String userMessage, String aiResponse,
                                         String sessionId) {
        updateConversationHistory(conversationId, userMessage, aiResponse);
        saveConversationToHistory(userId, conversationId);
        try {
            conversationService.recordConversationWithConversationId(userId, conversationId, userMessage, aiResponse);
        } catch (Exception e) {
            logger.error("对话落库 MySQL 失败（Redis 已保存），用户: {}, 会话: {}, 原因: {}",
                    userId, conversationId, e.getMessage(), e);
        }
        sessionUserMapping.remove(sessionId);
        String redisKey = "user:" + userId + ":current_conversation";
        logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
    }

    private void sendResponseChunk(ChatOutput output, String chunk) {
        try {
            if (Boolean.TRUE.equals(stopFlags.get(output.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            if (Boolean.TRUE.equals(blockedFlags.get(output.getId()))) {
                return;
            }
            Map<String, String> chunkResponse = Map.of("type", "response_chunk", "content", chunk != null ? chunk : "");
            output.send(chunkResponse);
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(ChatOutput output) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "response_complete",
                "status", "finished",
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            output.send(notification);
            output.complete();
            logger.info("已发送响应完成通知到会话: {}", output.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void sendConversationId(ChatOutput output, String conversationId) {
        try {
            Map<String, String> payload = Map.of("type", "conversation_id", "conversationId", conversationId);
            output.send(payload);
        } catch (Exception e) {
            logger.error("发送会话ID失败: {}", e.getMessage(), e);
        }
    }

    public void sendRefuseMessage(ChatOutput output, String reason) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                    "type", "refuse",
                    "message", reason,
                    "timestamp", currentTime,
                    "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            output.send(response);
        } catch (Exception e) {
            logger.error("发送敏感词拦截消息失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(ChatOutput output, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("type", "error", "message", "AI服务暂时不可用，请稍后重试");
            output.send(errorResponse);
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, String sessionId) {
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        stopFlags.put(sessionId, true);

        // 真正中断底层 LLM 流
        Disposable disposable = activeDisposables.get(sessionId);
        if (disposable != null) {
            try {
                disposable.dispose();
            } catch (Exception ignored) {
            }
            activeDisposables.remove(sessionId);
        }

        // 注意：SSE 通道的关闭由 Controller 在收到停止请求后调用 output.complete() 完成，
        // 此处仅设置停止标志并中断 LLM 流，避免继续推送后续 chunk。

        new Thread(() -> {
            try {
                Thread.sleep(2000);
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    public String getReferenceMd5(String sessionId, int referenceNumber) {
        logger.info("查询引用MD5: sessionId={}, referenceNumber=#{}", sessionId, referenceNumber);
        Map<Integer, String> referenceMapping = sessionReferenceMappings.get(sessionId);
        if (referenceMapping == null) {
            logger.error("未找到会话 {} 的引用映射，当前所有会话: {}", sessionId, sessionReferenceMappings.keySet());
            return null;
        }
        logger.info("会话 {} 的引用映射内容: {}", sessionId, referenceMapping);
        String fileMd5 = referenceMapping.get(referenceNumber);
        if (fileMd5 == null) {
            logger.error("会话 {} 中未找到引用编号 #{}, 可用的引用编号: {}", sessionId, referenceNumber, referenceMapping.keySet());
            return null;
        }
        logger.info("成功找到引用映射: sessionId={}, referenceNumber=#{}, fileMd5={}", sessionId, referenceNumber, fileMd5);
        return fileMd5;
    }

    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, String> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("清理会话 {} 的引用映射，共 {} 条", sessionId, removed.size());
        }
    }
}
